[build]
builder = "nixpacks"

[build.nixpacksConfig]
providers = ["python"]

[build.nixpacksConfig.python]
version = "3.11"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT --workers 2 --timeout 30 app:app"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10